# Generated by Django 3.0.4 on 2020-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocja', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('adres_ulica', models.CharField(max_length=100)),
                ('adres_miasto', models.CharField(max_length=50)),
                ('adres_kod', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TowarWZamowieniu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('produkt', models.ManyToManyField(to='sklep.Produkt')),
                ('zamowienie', models.ManyToManyField(to='sklep.Zamowienie')),
            ],
        ),
    ]
